Update get_metric_data.py
Current super was causing a TypeError:

super(GetAppHealthStatusAction, Action).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type

Changing to super(GetAppHealthStatusAction, self) resolves the issue and things are working correctly again.